/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

/**
 *
 * @author souza
 */
public class CADASTRAR extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public CADASTRAR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel PainelRosa = new javax.swing.JPanel();
        jLabelENTRAR = new javax.swing.JLabel();
        jLabelSENHA = new javax.swing.JLabel();
        CAMPOUSUARIO = new javax.swing.JTextField();
        jLabelUSUARIO = new javax.swing.JLabel();
        CAMPOSENHA = new javax.swing.JPasswordField();
        jButtonENVIAR = new javax.swing.JButton();
        jButtoVOLTAR = new javax.swing.JButton();
        jLabelFUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelRosa.setBackground(new java.awt.Color(243, 215, 231));
        PainelRosa.setMaximumSize(new java.awt.Dimension(500, 80));

        jLabelENTRAR.setFont(new java.awt.Font("SimSun", 0, 30)); // NOI18N
        jLabelENTRAR.setText("Cadastrar");

        jLabelSENHA.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        jLabelSENHA.setText("Senha:");

        jLabelUSUARIO.setFont(new java.awt.Font("SimSun", 0, 20)); // NOI18N
        jLabelUSUARIO.setText("Usuario:");

        jButtonENVIAR.setBackground(new java.awt.Color(238, 137, 213));
        jButtonENVIAR.setText("Eviar");
        jButtonENVIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENVIARActionPerformed(evt);
            }
        });

        jButtoVOLTAR.setBackground(new java.awt.Color(238, 137, 213));
        jButtoVOLTAR.setText("Voltar");
        jButtoVOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoVOLTARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelRosaLayout = new javax.swing.GroupLayout(PainelRosa);
        PainelRosa.setLayout(PainelRosaLayout);
        PainelRosaLayout.setHorizontalGroup(
            PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRosaLayout.createSequentialGroup()
                .addGroup(PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelSENHA)
                            .addComponent(CAMPOUSUARIO)
                            .addComponent(jLabelUSUARIO)
                            .addComponent(CAMPOSENHA, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)))
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtoVOLTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonENVIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabelENTRAR)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        PainelRosaLayout.setVerticalGroup(
            PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRosaLayout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(jLabelENTRAR)
                .addGap(42, 42, 42)
                .addComponent(jLabelUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAMPOUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAMPOSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonENVIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtoVOLTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        getContentPane().add(PainelRosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 480, 980));

        jLabelFUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/Fundo Flores.jpg"))); // NOI18N
        getContentPane().add(jLabelFUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonENVIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENVIARActionPerformed
        //botao de enviar
    }//GEN-LAST:event_jButtonENVIARActionPerformed

    private void jButtoVOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoVOLTARActionPerformed
        LOGIN login = new LOGIN ();
        login.setVisible(true);
    }//GEN-LAST:event_jButtoVOLTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CADASTRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CADASTRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CADASTRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CADASTRAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CADASTRAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CAMPOSENHA;
    private javax.swing.JTextField CAMPOUSUARIO;
    private javax.swing.JButton jButtoVOLTAR;
    private javax.swing.JButton jButtonENVIAR;
    private javax.swing.JLabel jLabelENTRAR;
    private javax.swing.JLabel jLabelFUNDO;
    private javax.swing.JLabel jLabelSENHA;
    private javax.swing.JLabel jLabelUSUARIO;
    // End of variables declaration//GEN-END:variables
}
