/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

import javax.swing.*;
import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author souza
 */
public class CUSTOS extends javax.swing.JFrame {
    
    private CADASTRAR_INGREDIENTE painelCadastroIngredientes;
    private JDialog dialog;

    public CUSTOS() {
        initComponents();
        painelCadastroIngredientes = new CADASTRAR_INGREDIENTE(this);
        painelCadastroIngredientes.setVisible(false);
        getContentPane().add(painelCadastroIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 600));
        extrairdados();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel PainelRosa = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela_custos = new javax.swing.JTable();
        jButtonVOLTAR1 = new javax.swing.JButton();
        Botao_adicionar = new javax.swing.JButton();
        Botao_atualizar = new javax.swing.JButton();
        Botao_editar = new javax.swing.JButton();
        Botao_excluir = new javax.swing.JButton();
        jLabelFUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelRosa.setBackground(new java.awt.Color(243, 215, 231));
        PainelRosa.setMaximumSize(new java.awt.Dimension(500, 80));

        Tabela_custos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabela_custos);

        jButtonVOLTAR1.setBackground(new java.awt.Color(238, 137, 213));
        jButtonVOLTAR1.setText("Voltar");
        jButtonVOLTAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVOLTAR1ActionPerformed(evt);
            }
        });

        Botao_adicionar.setText("Adicionar");
        Botao_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_adicionarActionPerformed(evt);
            }
        });

        Botao_atualizar.setText("Atualizar");
        Botao_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_atualizarActionPerformed(evt);
            }
        });

        Botao_editar.setText("Editar");
        Botao_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_editarActionPerformed(evt);
            }
        });

        Botao_excluir.setText("Excluir");
        Botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelRosaLayout = new javax.swing.GroupLayout(PainelRosa);
        PainelRosa.setLayout(PainelRosaLayout);
        PainelRosaLayout.setHorizontalGroup(
            PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRosaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addComponent(Botao_adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Botao_atualizar)))
                .addContainerGap())
            .addGroup(PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRosaLayout.createSequentialGroup()
                    .addContainerGap(200, Short.MAX_VALUE)
                    .addComponent(jButtonVOLTAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(180, 180, 180)))
        );
        PainelRosaLayout.setVerticalGroup(
            PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRosaLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_adicionar)
                    .addComponent(Botao_editar)
                    .addComponent(Botao_excluir)
                    .addComponent(Botao_atualizar))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelRosaLayout.createSequentialGroup()
                    .addContainerGap(915, Short.MAX_VALUE)
                    .addComponent(jButtonVOLTAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );

        getContentPane().add(PainelRosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 480, 980));

        jLabelFUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/Fundo Flores.jpg"))); // NOI18N
        getContentPane().add(jLabelFUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    public void extrairdados() {
        DefaultTableModel model = (DefaultTableModel) Tabela_custos.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Nome", "Valor", "Quantidade(kg)", "CustoPorUnidade"});

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/trabalhopi", "root", "5563");
            Statement stmt = conn.createStatement();
            String query = "select custo_variavel.Icredientes as Nome, " +
                         "custo_variavel.Valor as Valor, " +
                         "custo_variavel.Quantidade as Quantidade, " +
                         "unidade_custo_variavel.total as Custo_Por_Unidade " +
                         "from custo_variavel " +
                         "INNER JOIN unidade_custo_variavel on custo_variavel.id_Variavel= unidade_custo_variavel.fk_id_Variavel";
            ResultSet resultado_pesquisa = stmt.executeQuery(query);

            while (resultado_pesquisa.next()) {
                String Nome = resultado_pesquisa.getString("Nome");
                double Valor = resultado_pesquisa.getDouble("Valor");
                double Quantidade = resultado_pesquisa.getDouble("Quantidade");
                double CustoPorUnidade = resultado_pesquisa.getDouble("Custo_Por_Unidade");
                
                //System.out.println("Adding row: " + id + ", " + nome + ", " + valor + ", " + quantidade + ", " + unidade);
                //model.addRow(new Object[]{id, nome, valor, quantidade, Unidade_Medida});
                
                model.addRow(new Object[]{Nome, Valor, Quantidade, CustoPorUnidade});
            }
            Tabela_custos.setModel(model);

            resultado_pesquisa.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void jButtonVOLTAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVOLTAR1ActionPerformed
     dispose(); 
     MENUBANCO menubanco = new MENUBANCO();
     menubanco.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVOLTAR1ActionPerformed

    private void Botao_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_adicionarActionPerformed
    System.out.println("Botão Adicionar clicado!"); 

    // Verifica se o painel está inicializado
    if (painelCadastroIngredientes!= null) {
        // Cria uma nova janela para o painel
        CADASTRAR_INGREDIENTE painelCadastroIngredientes = new CADASTRAR_INGREDIENTE(this);

            dialog = new JDialog(CUSTOS.this, "Cadastro de Ingredientes", true);
            dialog.setSize(980, 600);
            dialog.setLocationRelativeTo(null);

            dialog.getContentPane().add(painelCadastroIngredientes, BorderLayout.CENTER);

            dialog.setVisible(true);
    } else {
        System.err.println("Erro: painelCadastroIngredientes não inicializado.");
    }    // TODO add your handling code here:
    }//GEN-LAST:event_Botao_adicionarActionPerformed

    private void Botao_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_atualizarActionPerformed
    System.out.println("Botão Atualizar clicado!");
    extrairdados();    // TODO add your handling code here:
    }//GEN-LAST:event_Botao_atualizarActionPerformed

    private void Botao_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_editarActionPerformed
       int selectedRow = Tabela_custos.getSelectedRow();
    if (selectedRow != -1) {
        String nome = (String) Tabela_custos.getValueAt(selectedRow, 0);
        double valor = (Double) Tabela_custos.getValueAt(selectedRow, 1);
        double quantidade = (Double) Tabela_custos.getValueAt(selectedRow, 2);
        
        CADASTRAR_INGREDIENTE painelEdicao = new CADASTRAR_INGREDIENTE(this, nome, valor, quantidade);
        dialog = new JDialog(CUSTOS.this, "Editar Ingrediente", true);
        dialog.setSize(980, 600);
        dialog.setLocationRelativeTo(null);
        dialog.getContentPane().add(painelEdicao, BorderLayout.CENTER);
        dialog.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecione um ingrediente para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_Botao_editarActionPerformed

    private void Botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_excluirActionPerformed
     int selectedRow = Tabela_custos.getSelectedRow();
    if (selectedRow != -1) {
        String nome = (String) Tabela_custos.getValueAt(selectedRow, 0);

        int confirm = JOptionPane.showConfirmDialog(this, "Você tem certeza que deseja excluir o ingrediente " + nome + "?", "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            excluirIngrediente(nome);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecione um ingrediente para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }   // TODO add your handling code here:
    }//GEN-LAST:event_Botao_excluirActionPerformed
   
    private void abrirCadastroIngredientes() {
        painelCadastroIngredientes.setVisible(true);
    }

    public void fecharCadastroIngredientes() {
         if (dialog!= null && dialog.isVisible()) {
        dialog.dispose(); 
    }
    }
    
    private void excluirIngrediente(String nome) {
        Connection conn = null;
        PreparedStatement pstmt = null;
        PreparedStatement pstmtUni = null;

        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/trabalhopi", "root", "5563");
            conn.setAutoCommit(false);

            // Exclua primeiro da tabela unidade_custo_variavel
            String sqlUni = "DELETE FROM unidade_custo_variavel WHERE fk_id_Variavel = (SELECT id_Variavel FROM custo_variavel WHERE Icredientes = ?)";
            pstmtUni = conn.prepareStatement(sqlUni);
            pstmtUni.setString(1, nome);
            pstmtUni.executeUpdate();

            // Em seguida, exclua da tabela custo_variavel
            String sql = "DELETE FROM custo_variavel WHERE Icredientes = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, nome);
            pstmt.executeUpdate();

            conn.commit();
        } catch (SQLException e) {
            if (conn != null) {
                try {
                    conn.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            e.printStackTrace();
        } finally {
            if (pstmt != null) {
                try {
                    pstmt.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (pstmtUni != null) {
                try {
                    pstmtUni.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CUSTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CUSTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CUSTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CUSTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUSTOS().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_adicionar;
    private javax.swing.JButton Botao_atualizar;
    private javax.swing.JButton Botao_editar;
    private javax.swing.JButton Botao_excluir;
    private javax.swing.JTable Tabela_custos;
    private javax.swing.JButton jButtonVOLTAR1;
    private javax.swing.JLabel jLabelFUNDO;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
