/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

/**
 *
 * @author souza
 */
public class MENU1 extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public MENU1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel PainelRosa = new javax.swing.JPanel();
        jLabelMENU = new javax.swing.JLabel();
        jButtonPRECIFICAÇÃO = new javax.swing.JButton();
        jButtonVOLTAR1 = new javax.swing.JButton();
        jButtonBANCO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelRosa.setBackground(new java.awt.Color(243, 215, 231));
        PainelRosa.setMaximumSize(new java.awt.Dimension(500, 80));

        jLabelMENU.setFont(new java.awt.Font("SimSun", 0, 30)); // NOI18N
        jLabelMENU.setText("MENU");

        jButtonPRECIFICAÇÃO.setBackground(new java.awt.Color(238, 160, 216));
        jButtonPRECIFICAÇÃO.setText("Precificação");
        jButtonPRECIFICAÇÃO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPRECIFICAÇÃOActionPerformed(evt);
            }
        });

        jButtonVOLTAR1.setBackground(new java.awt.Color(238, 160, 216));
        jButtonVOLTAR1.setText("Voltar");
        jButtonVOLTAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVOLTAR1ActionPerformed(evt);
            }
        });

        jButtonBANCO.setBackground(new java.awt.Color(238, 160, 216));
        jButtonBANCO.setText("Banco de dados");
        jButtonBANCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBANCOActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/logo_1.png"))); // NOI18N

        javax.swing.GroupLayout PainelRosaLayout = new javax.swing.GroupLayout(PainelRosa);
        PainelRosa.setLayout(PainelRosaLayout);
        PainelRosaLayout.setHorizontalGroup(
            PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRosaLayout.createSequentialGroup()
                .addGroup(PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPRECIFICAÇÃO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBANCO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabelMENU))
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButtonVOLTAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        PainelRosaLayout.setVerticalGroup(
            PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRosaLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jLabelMENU)
                .addGap(38, 38, 38)
                .addComponent(jButtonBANCO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPRECIFICAÇÃO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonVOLTAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        getContentPane().add(PainelRosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 480, 980));

        jLabelFUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/Fundo Flores.jpg"))); // NOI18N
        getContentPane().add(jLabelFUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBANCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBANCOActionPerformed
        MENUBANCO bancodados = new MENUBANCO();
        bancodados.setVisible(true);
    }//GEN-LAST:event_jButtonBANCOActionPerformed

    private void jButtonVOLTAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVOLTAR1ActionPerformed
        LOGIN login = new LOGIN();
        login.setVisible(true);
    }//GEN-LAST:event_jButtonVOLTAR1ActionPerformed

    private void jButtonPRECIFICAÇÃOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPRECIFICAÇÃOActionPerformed
        PRECIFICACAO calculadora = new PRECIFICACAO();
        calculadora.setVisible(true);
    }//GEN-LAST:event_jButtonPRECIFICAÇÃOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBANCO;
    private javax.swing.JButton jButtonPRECIFICAÇÃO;
    private javax.swing.JButton jButtonVOLTAR1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFUNDO;
    private javax.swing.JLabel jLabelMENU;
    // End of variables declaration//GEN-END:variables
}
