/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

/**
 *
 * @author souza
 */
public class MENUBANCO extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public MENUBANCO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel PainelRosa = new javax.swing.JPanel();
        jLabelBANCODEDADOS = new javax.swing.JLabel();
        jButtonRECEITAS = new javax.swing.JButton();
        jButtonVOLTAR1 = new javax.swing.JButton();
        jButtonCUSTO = new javax.swing.JButton();
        jLabelFUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelRosa.setBackground(new java.awt.Color(243, 215, 231));
        PainelRosa.setMaximumSize(new java.awt.Dimension(500, 80));

        jLabelBANCODEDADOS.setFont(new java.awt.Font("SimSun", 0, 30)); // NOI18N
        jLabelBANCODEDADOS.setText("BANCO DE DADOS");

        jButtonRECEITAS.setBackground(new java.awt.Color(238, 160, 216));
        jButtonRECEITAS.setText("Receitas");
        jButtonRECEITAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRECEITASActionPerformed(evt);
            }
        });

        jButtonVOLTAR1.setBackground(new java.awt.Color(238, 160, 216));
        jButtonVOLTAR1.setText("Voltar");
        jButtonVOLTAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVOLTAR1ActionPerformed(evt);
            }
        });

        jButtonCUSTO.setBackground(new java.awt.Color(238, 160, 216));
        jButtonCUSTO.setText("Custo");
        jButtonCUSTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCUSTOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelRosaLayout = new javax.swing.GroupLayout(PainelRosa);
        PainelRosa.setLayout(PainelRosaLayout);
        PainelRosaLayout.setHorizontalGroup(
            PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRosaLayout.createSequentialGroup()
                .addGroup(PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButtonVOLTAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabelBANCODEDADOS))
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jButtonCUSTO, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelRosaLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButtonRECEITAS, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        PainelRosaLayout.setVerticalGroup(
            PainelRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRosaLayout.createSequentialGroup()
                .addContainerGap(389, Short.MAX_VALUE)
                .addComponent(jLabelBANCODEDADOS)
                .addGap(18, 18, 18)
                .addComponent(jButtonCUSTO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRECEITAS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonVOLTAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        getContentPane().add(PainelRosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 480, 980));

        jLabelFUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/Fundo Flores.jpg"))); // NOI18N
        getContentPane().add(jLabelFUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCUSTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCUSTOActionPerformed
        CUSTOS custos = new CUSTOS ();
        custos.setVisible(true);
    }//GEN-LAST:event_jButtonCUSTOActionPerformed

    private void jButtonVOLTAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVOLTAR1ActionPerformed
        MENU1 menu1 = new MENU1();
        menu1.setVisible(true);
    }//GEN-LAST:event_jButtonVOLTAR1ActionPerformed

    private void jButtonRECEITASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRECEITASActionPerformed
        RECEITAS receitas = new RECEITAS();
        receitas.setVisible(true);
    }//GEN-LAST:event_jButtonRECEITASActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENUBANCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENUBANCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENUBANCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENUBANCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENUBANCO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCUSTO;
    private javax.swing.JButton jButtonRECEITAS;
    private javax.swing.JButton jButtonVOLTAR1;
    private javax.swing.JLabel jLabelBANCODEDADOS;
    private javax.swing.JLabel jLabelFUNDO;
    // End of variables declaration//GEN-END:variables
}
